### ISSUE TITLE
Refusing to run without usable config file!

### ISSUE THREAD

**Issue by kendoori** [vmatare/thinkfan#126]
Am running TF on Linux Mint 20.1

Running: service thinkfan status yields the following

![root@kenny-ThinkPad-T480: -home-kenny_059](https://user-images.githubusercontent.com/2447420/107411913-15bda980-6add-11eb-986b-9ceed9268ffc.png)

My config file was built from this list
![root@kenny-ThinkPad-T480: -home-kenny_061](https://user-images.githubusercontent.com/2447420/107412017-34bc3b80-6add-11eb-9302-cd53b698aee6.png)

My thinkfan.conf looks like this:
![root@kenny-ThinkPad-T480: -home-kenny_060](https://user-images.githubusercontent.com/2447420/107412222-6c2ae800-6add-11eb-8ae3-8688e6724a29.png)

**Comment by kendoori** [comment]
FYI, the config here worked: https://gist.github.com/Yatoom/1c80b8afe7fa47a938d3b667ce234559#gistcomment-3306472

**Comment by vmatare** [comment]
This looks a lot like thinkfan might be trying to start before the necessary modules have been loaded. That said, the 0.9.1 release is ancient, so please try with a newer version (and tell your distribution to update the thinkfan package). If the problem persists with the latest thinkfan release, you're probably experiencing issue #118. So then you'd want to read up on #118 and try the workarounds mentioned there until I've found the time to implement a proper fix.
