### ISSUE TITLE
Force full-speed mode?

### ISSUE THREAD

**Issue by musikerv** [vmatare/thinkfan#13]
Hello everyone.

I have a thinkpad e420.
thinkfan 0.99.0

Is there a way to force the fan to operate at full-speed for some time (or in sothething like on-off mode) for high environment temp conditions????
A simple command?  Or a config script?
Should i use simple or complex config? 
thanks

**Comment by vmatare** [comment]
All of these questions should be answered by the config man page
`man thinkfan.conf`
If you haven't read it, please do. If you did and it remains unclear, I'll be happy to improve it if you elaborate on what exactly you're trying to achieve.

**Comment by musikerv** [comment]
I opened it and tried but not straightforward how to do it. Something like 'setting level 7 or 255 in /proc/acpi/ibm/fan.
Will try this again later today and report back.
thanks for quick reply...

**Comment by Andrei-Pozolotin** [comment]
I confirm that full speed entry works:
``
("level full-speed", 75, 32767) # 5000 rpm
``

**Comment by musikerv** [comment]
OK! in Fedora I got 'su' access and then
`echo level full-speed > /proc/acpi/ibm/fan`

then I tested with
`cat /proc/acpi/ibm/fan`
and the output is: 
`status:		enabled
speed:		0
level:		disengaged
commands:	level <level> (<level> is 0-7, auto, disengaged, full-speed)
commands:	enable, disable
commands:	watchdog <timeout> (<timeout> is 0 (off), 1-120 (seconds))
`

so it gets enabled but the level seems to be disengaged...
but with `echo level 7 > /proc/acpi/ibm/fan` it seems to accept the value... 
still cannot hear the fan spinning full, so I am just trying..

p.s. do we still have connection to [these](http://www.thinkwiki.org/wiki/How_to_control_fan_speed) guys? there are some instructions relative to the older thinkfan versions there.

thanks

**Comment by vmatare** [comment]
`full-speed` is the same as `disengaged`. You have to wait a minute for the fan speed to ramp up. All of this has nothing to do with thinkfan, you can uninstall it if you just want to control your fan speed manually. The `thinkpad_acpi` kernel module is responsible for `/proc/acpi/ibm/*`. Please read its documentation [here](https://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/tree/Documentation/laptops/thinkpad-acpi.txt?id=refs/tags/v4.5.7).

**Comment by musikerv** [comment]
OK. I am reading this now. I still use thinkfan, and just in special cases intend to use the manual  feature if at all.
So, in my opinion this topic is actually a documentation related one since I know now how to setup properlly the conf file.

cheers

**Comment by schplorg** [comment]
> OK! in Fedora23 I got 'su' access and then: `echo level full-speed > /proc/acpi/ibm/fan`
> 
> then I tested with `cat /proc/acpi/ibm/fan` and the output is: `status: enabled speed: 0 level: disengaged commands: level <level> (<level> is 0-7, auto, disengaged, full-speed) commands: enable, disable commands: watchdog <timeout> (<timeout> is 0 (off), 1-120 (seconds)) `
> 
> so it gets enabled but the level seems to be disengaged... but with `echo level 7 > /proc/acpi/ibm/fan` it seems to accept the value... still cannot hear the fan spinning full, so I am just trying..
> 
> p.s. do we still have connection to [these](http://www.thinkwiki.org/wiki/How_to_control_fan_speed) guys? there are some instructions relative to the older thinkfan versions there.
> 
> thanks

This worked great with my Thinkpad T14 Gen3 AMD on Fedora 38
