### ISSUE TITLE
Log all fan changes

### ISSUE THREAD

**Issue by MerzDaniel** [vmatare/thinkfan#173]
Currently thinkfan only logs on startup and on errors (Ubuntu 21.04). I'd like to see a log entry whenever the fan level changes

**Comment by vmatare** [comment]
Run `thinkfan -h`, it should tell you what to do...

**Comment by vmatare** [comment]
oh wait, on Ubuntu you might have an ancient version (0.9.*). The logging behavior has improved much since then ;-)

**Comment by vmatare** [comment]
Closing since this has been implemented for a long time and is documented in both the manpage and in the help screen.
