### ISSUE TITLE
Can't get thinkfan to run, doesn't find /sys/devices/pci.../hwmon

### ISSUE THREAD

**Issue by Chrissi43** [vmatare/thinkfan#200]
Hallo,

I have a huge problem with thinkfan. It's really a great software. So far i have had no problems. Now after I upgraded to a newer linux system I can no longer get the software to run. I'm not a software engineer, only a boring normal computer user. I have no idea what the problem is. Maybe someone here knows a solution?

### My system consists of

- Kernel: 5.10.0-18-amd64 [5.10.140-1] x86_64
- init=/lib/systemd/systemd
- Distro: MX-21.2.1_x64 Wildflower April 9  2022
- base: Debian GNU/Linux 11 (bullseye)
- Machine: Laptop System: LENOVO product: 3680HSG v: ThinkPad X201

### What I have done so far

- I followed the instructions for installation and setup as indicated here: [https://thinkwiki.de/Thinkfan](url) -- I used this instruction for my older system before and everything was fine.
- So I installed the packages "thinkfan" (1.2.1-3~mx21+1) and "lm-sensors" (1:3.6.0-7) from the normal package sources without an error.
- I created the file `/etc/modprobe.d/thinkfan.conf` with the content `options thinkpad_acpi fan_control=1`
- I looked after the temperature control devices with `find /sys/devices -type f -name "temp*_input"`
- Then I created the file `/etc/thinkfan.conf`with these informations. Here is the content of this file:

```
hwmon /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon2/temp6_input
hwmon /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon2/temp3_input
hwmon /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon2/temp7_input
hwmon /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon2/temp4_input
hwmon /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon2/temp8_input
hwmon /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon2/temp1_input
hwmon /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon2/temp5_input
hwmon /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon2/temp2_input
hwmon /sys/devices/platform/coretemp.0/hwmon/hwmon3/temp4_input
hwmon /sys/devices/platform/coretemp.0/hwmon/hwmon3/temp2_input

(0,	0,	60)
(1,	60,	65)
(2,	65,	70)
(3,	70,	75)
(4,	75,	80)
(5,	80,	85)
(7,	85,	32767)
```
- I rebooted my system

### Testing the installation

- After reboot I tested thinkfan with the command `sudo thinkfan -n`
- It gave me this error: `ERROR: Error scanning /sys/devices/pci0000:00/0000:00:03.1/0000:27:00.0/hwmon: No such file or directory`

### Solution?

I am quite perplexed, since everything has run without problems so far with the old system. I also do not find my problem described on the Internet or here in the forum. I have not yet dared to compile the program with the newest version myself. I have no idea about compiling and have not needed it yet. Does anyone know advice?

Thanks in advance for any help,
Chrissi

**Comment by g1th** [comment]
Does the thinkpad_acpi load in /etc/modprobe.d properly?

**Comment by g1th** [comment]
> Hallo ThaungHan,
> 
> thank you for your time and question. I checked with `lsmod` whether "thinkpad_acpi" is loading. Among other things, the output lists the module, but with a zero. So if I understand it right the module is being loaded but not used?

" I created the file /etc/modprobe.d/thinkfan.conf with the content options thinkpad_acpi fan_control=1 "

I think the thinkpad_acpi.conf path should be in /etc/modprobe.d/ thinkpad_acpi.conf  and  fan config file should be in /etc/thinkfan.conf imo.

And also you should cat /proc/acpi/ibm/fan is enabled or not. If the output is enabled and thing still does not work, you should unload the module first "modprobe -r thinkpad_acpi"and load again "modprobe thinkpad_acpi. I think it would work. Pls keep in mind that I'm also a user and thinkfan is broken many times by my messing up.  Hope it work out for you. Thank you.

**Comment by vmatare** [comment]
@Chrissi43 have you taken a look at your hwmon hierarchy to see what's actually in there? I'd recommend looking at `/sys/class/hwmon`. Either use those paths directly or look where the symlinks point.

**Comment by vmatare** [comment]
Oh and please don't put much trust in 3rd party instructions, in particular don't expect you can just copy&paste configs from the internet. Read the `thinkfan.conf` manpage and pay particular attention to the documentation of the `hwmon` path specification and the related `indices` and `name` entries.
