### ISSUE TITLE
ERROR: TpFanDriver: Initializing fan control in /proc/acpi/ibm/fan: Success

### ISSUE THREAD

**Issue by free-city-of-ulm** [vmatare/thinkfan#22]
Running thinkfan produces `ERROR: TpFanDriver: Initializing fan control in /proc/acpi/ibm/fan: Success` and nothing else.

**Comment by vmatare** [comment]
This should be fixed in the current master. If you can, please pull a fresh copy from github. If there is something wrong with your setup, it should at least give a much more helpful error message.

**Comment by free-city-of-ulm** [comment]
I am on the current master and I started getting this error after updating.  Is there any way to get more debug information for you?

**Comment by vmatare** [comment]
Oh sorry, dumb oversight in one of the recent commits. Fix in progress ;-)

**Comment by vmatare** [comment]
Ok, should be fixed by commit eda4f28

**Comment by free-city-of-ulm** [comment]
Fixed
