### ISSUE TITLE
setting RPM that corresponds to the speed levels manually 

### ISSUE THREAD

**Issue by smautner** [vmatare/thinkfan#234]
Hi, Haven't found an issue on this obvious item so here i go. 

I have an T14 gen 4 AMD, level 1 maps to a fan speed that is too loud, so was wondering if there is a solution to this.
Is there an easy way to map the speed levels to actual fan-speeds?

**Comment by smautner** [comment]
Thank you. Working without rpm mapping, I haven't found a setting i like. I also figured that increasing the temperature range for level 0 is important, but going auto never occurred to me.

**Comment by vmatare** [comment]
On thinkpads the embedded controller only exposes certain fixed levels to userspace. If you use the hwmon interface, values theoretically range from 0 to 255, but in my experience, thinkpad ECs also quantize these into a small number of fixed levels. So yeah, the best advice to get some smoothness is to use `level auto` and only configure explicit levels at the top and bottom end of the temperature range.
