### ISSUE TITLE
ERROR: TpSensorDriver

### ISSUE THREAD

**Issue by Sulter** [vmatare/thinkfan#33]
When I'm trying to run thinkfan I get the following message:
```
root@sulter:~# thinkfan -c /etc/thinkfan.conf

ERROR: TpSensorDriver: Initializing sensor in /proc/acpi/ibm/thermal: Succes
```
I'm using the default config file:

> (0,     0,      55)
> (1,     50,     60)
> (2,     55,     61)
> (3,     56,     63)
> (4,     57,     65)
> (5,     59,     66)
> (7,     63,     32767)

I'm able to manipulate /proc/acpi/ibm/thermal manually without any problems.

**Comment by vmatare** [comment]
Which version are you using?

**Comment by Sulter** [comment]
Commit 3b4589cb31e95c48327750f006847f00e32c2668
The newest version.
I guess I should try the release instead?

**Comment by Sulter** [comment]
I can confirm that 1.0 beta3 has the same issue, while 1.0 beta1 works just fine.

**Comment by knochenhans** [comment]
Hi, not sure if that helps, but I got exactly the same behaviour here (L420), so latest release gives me the TpSensorDriver error while 1.0 beta1 works without problems.

**Comment by vmatare** [comment]
Dumb question: Does `/proc/acpi/ibm/thermal` even exist? I'm asking because on recent systems, it usually doesn't exist any more...

**Comment by knochenhans** [comment]
It exists for me (using kernel 4.10.8):
`cat /proc/acpi/ibm/thermal                                   
temperatures:	47 0 47 0 31 54 24 54`

**Comment by vmatare** [comment]
Well, sorry it took so long, but to test this I actually had to dig an old T42 from the shelves ;-)
Anyways, the problem should be fixed now in the current master.

**Comment by vmatare** [comment]
Closing for lack of feedback after the fix was pushed.
