### ISSUE TITLE
/proc/acpi/ibm/thermal doesn't exist T520

### ISSUE THREAD

**Issue by The-Soulless** [vmatare/thinkfan#52]
Hello, I'm using a T520 and trying to get Thinkfan to work on Void GNU/Linux. I have copied the simple config but wen I run it I get the following error:
https://hastebin.com/kegavadeku.pas

**Comment by emmanuelgeoffray** [comment]
same

**Comment by emmanuelgeoffray** [comment]
I followed the insturctions there to fix it: http://thinkwiki.de/Thinkfan
```
Nun können die verfügbaren Temperatursensoren mit folgendem Kommando angezeigt werden:

find /sys/devices -type f -name "temp*_input"
Die Ausgabezeilen nimmt mit man einem vorangestellten sensor in /etc/thinkfan.conf auf (vor den Temperaturschwellen).

Beispiel (T420s):

sensor /sys/devices/platform/coretemp.0/temp1_input
sensor /sys/devices/platform/coretemp.2/temp1_input
sensor /sys/devices/virtual/hwmon/hwmon0/temp1_input```

**Comment by vmatare** [comment]
Pastebin is empty. Is this still an issue?

**Comment by DEvil0000** [comment]
works on my L480 with:
```
hwmon /sys/devices/platform/coretemp.0/temp1_input
...
```

**Comment by jorgelaranjo** [comment]
On a Thinkstation P700 folder `/proc/acpi/ibm/thermal` does not exist. `/sys/devices/platform/coretemp.*/` exist but those don't show any fans nor fan control whatsoever.
Lenovo does say this machine is certified for Ubuntu and CentOS but neither seems to show fan control as my experience shows and the following link [https://askubuntu.com/questions/1238028/how-to-control-fan-speed-on-thinkstation-by-lenovo](shows)

Would be nice to know if fan control is possible under Linux for this platform and which kernel modules need to be loaded.
`thinkpad_acpi does not load.`
