### ISSUE TITLE
libboost requirement?

### ISSUE THREAD

**Issue by clickworkorange** [vmatare/thinkfan#54]
Trying to compile this but it fails when not finding libboost: 
````
In file included from /usr/include/yaml-cpp/node/node.h:16:0,
                 from /usr/include/yaml-cpp/yaml.h:16,
                 from /home/ola/Sources/thinkfan/src/yamlconfig.h:9,
                 from /home/ola/Sources/thinkfan/src/config.cpp:31:
/usr/include/yaml-cpp/node/ptr.h:11:32: fatal error: boost/shared_ptr.hpp: No such file or directory
compilation terminated.
````
However: 
````
apt-get install libboost-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libboost1.58-dev
Suggested packages:
  libboost-doc libboost1.58-doc libboost-atomic1.58-dev libboost-chrono1.58-dev libboost-context1.58-dev libboost-coroutine1.58-dev libboost-date-time1.58-dev
  libboost-exception1.58-dev libboost-filesystem1.58-dev libboost-graph1.58-dev libboost-graph-parallel1.58-dev libboost-iostreams1.58-dev libboost-locale1.58-dev
  libboost-log1.58-dev libboost-math1.58-dev libboost-mpi1.58-dev libboost-mpi-python1.58-dev libboost-program-options1.58-dev libboost-python1.58-dev libboost-random1.58-dev
  libboost-regex1.58-dev libboost-serialization1.58-dev libboost-signals1.58-dev libboost-system1.58-dev libboost-test1.58-dev libboost-thread1.58-dev libboost-timer1.58-dev
  libboost-wave1.58-dev libboost1.58-tools-dev libmpfrc++-dev libntl-dev
The following NEW packages will be installed
  libboost-dev libboost1.58-dev
0 to upgrade, 2 to newly install, 0 to remove and 2 not to upgrade.
Need to get 6,225 kB of archives.
After this operation, 105 MB of additional disk space will be used.
Do you want to continue? [Y/n] HELL NO!
Abort.

````
A tad excessive, _for fan control_, isn't it? Also, this dependency isn't listed in the readme.

**Comment by clickworkorange** [comment]
Never mind; desperate to get the fan to behave on my X200 so I installed the ~150Mb worth of dependencies to get this to build (i.e. cmake-curses, libboost-dev, etc). But it does rankle my minimalist sensibilities that such a small program has such big dependencies just for building. I also couldn't avoid installing libyaml-cpp even with `-D USE_YAML:BOOL=False` (`make` resulted in `fatal error: yaml-cpp/yaml.h: No such file or directory`). This all said, it does seem to be working! :)

**Comment by vmatare** [comment]
Well, if you look closely, boost is actually not a direct dependency of thinkfan, but of the libyamlcpp you have installed. Unfortunately, certain distros still ship some ancient versions of libyamlcpp, and in your case it's so old that it still uses `boost::shared_ptr`.

That said, thinkfan should of course compile fine with `-D USE_YAML:BOOL=False`, so I'm reopening this to remind myself to look into that.
