### ISSUE TITLE
Won't compile on musl

### ISSUE THREAD

**Issue by gitlab-j** [vmatare/thinkfan#55]
Hi there, 

Thinkfan wasn't compiling on musl so I've whipped up a patch:

diff --git a/src/globaldefs.h b/src/globaldefs.h
index 75d3f6f..5a72e27 100644
--- a/src/globaldefs.h
+++ b/src/globaldefs.h
@@ -26,6 +26,7 @@
 #include <stdlib.h>
 #include <limits.h>
 #include <time.h>
+#include <sys/types.h>
 
 #define VERSION "0.9.1"

**Comment by vmatare** [comment]
Hey, thanks, could you make a pull request out of that so I can merge it while giving credit to you?

**Comment by vmatare** [comment]
Oh right, the Microsoft thing... well I don't have time right now, but I'll put a thinkfan repo on gitlab as soon as I find the time
