### ISSUE TITLE
fan stops for a moment after every timesleep (lenovo L480)

### ISSUE THREAD

**Issue by DEvil0000** [vmatare/thinkfan#56]
after every timesleep the fan is getting stopped/slowing down for a moment even if there is no change in level.

**Comment by vmatare** [comment]
Are you using depulsing mode (the `-p` option)? Because without it, if there is no change to the fan level, thinkfan does absolutely nothing to the fan. So without `-p` it's highly unlikely that thinkfan is causing that.

**Comment by DEvil0000** [comment]
well it is happening and exacly on sleeptime interval. if i change the sleeptime the fan slowdown is also changing to the same interval.no -p option is used. i used -n only, -n -s 1 and -n -b 1 -s 1 for testing.running ubuntu18.04 on the L480.
Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Victor Mataré <notifications@github.com> 
Datum: 26.07.2018  12:58  (GMT+01:00) 
An: vmatare/thinkfan <thinkfan@noreply.github.com> 
Cc: "A. Binzxxxxxx" <alexander@binzberger.de>, Author <author@noreply.github.com> 
Betreff: Re: [vmatare/thinkfan] fan stops for a moment after every timesleep
  (lenovo L480) (#56) 

Are you using depulsing mode (the -p option)? Because without it, if there is no change to the fan level, thinkfan does absolutely nothing to the fan. So without -p it's highly unlikely that thinkfan is causing that.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/vmatare/thinkfan","title":"vmatare/thinkfan","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/vmatare/thinkfan"}},"updates":{"snippets":[{"icon":"PERSON","message":"@vmatare in #56: Are you using depulsing mode (the `-p` option)? Because without it, if there is no change to the fan level, thinkfan does absolutely nothing to the fan. So without `-p` it's highly unlikely that thinkfan is causing that."}],"action":{"name":"View Issue","url":"https://github.com/vmatare/thinkfan/issues/56#issuecomment-408059237"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/vmatare/thinkfan/issues/56#issuecomment-408059237",
"url": "https://github.com/vmatare/thinkfan/issues/56#issuecomment-408059237",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [vmatare/thinkfan] fan stops for a moment after every timesleep (lenovo L480) (#56)",
"sections": [
{
"text": "",
"activityTitle": "**Victor Mataré**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@vmatare",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"vmatare/thinkfan\",\n\"issueId\": 56,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"vmatare/thinkfan\",\n\"issueId\": 56\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/vmatare/thinkfan/issues/56#issuecomment-408059237"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 361113043\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by vmatare** [comment]
Could you please post the config file you use and which thinkfan revision, i.e. `git show HEAD`...?

**Comment by DEvil0000** [comment]
seems like the issue was with a older version packaged in ubuntu 18.04. package version=0.9.3-2, thinkfan binary says 0.9.1 in the help.
however it works as expected with master.
thanks

**Comment by DEvil0000** [comment]
with the master version the fan is now slowing down when the level changes downwards. For example if the fan level goes from 7 to 5 the fan stops for a moment before it spins up again to the speed of 5 which is of course slower then 7.

**Comment by acarapetis** [comment]
Sadly, I think this is a hardware/firmware issue - I notice the same thing on my E480, but it's not thinkfan's problem: you can observe the same behaviour by manually adjusting the fan speed using `/proc/acpi/ibm/fan`, or even using tpfancontrol on Windows.

**Comment by vmatare** [comment]
Closing since this has been silent for a while and it's (probably) not fixable from within thinkfan.
