### ISSUE TITLE
Thinkfan crashes with built-in thinkpad_acpi

### ISSUE THREAD

**Issue by MatheusArtur** [vmatare/thinkfan#59]
It works normally on my thinkpad X220 with thinkpad_acpi as a module, but crashes when the kernel is compiled with builtin thinkpad_acpi.

**Comment by vmatare** [comment]
No one will be able to help you if don't give any information about the crash.

**Comment by MatheusArtur** [comment]
I don't have the kernel with built-in tp_acpi anymore, I'm closing the issue but I'll gather some info and maybe post here later.
