### ISSUE TITLE
Wrong error message on keyword mixup

### ISSUE THREAD

**Issue by StyXman** [vmatare/thinkfan#65]
I put this in my `thinkfan.conf` file:

    tp_thermal /sys/devices/virtual/thermal/thermal_zone0/temp

I test run `thinkfan`:

```
sudo thinkfan -n

/sys/devices/virtual/thermal/thermal_zone0/temp: No such file or directory

add_sensor: Error getting temperature.
Refusing to run without usable config file!
```

But:

```
$ namei -lx /sys/devices/virtual/thermal/thermal_zone0/temp
f: /sys/devices/virtual/thermal/thermal_zone0/temp
Drwxr-xr-x root root /
Dr-xr-xr-x root root sys
drwxr-xr-x root root devices
drwxr-xr-x root root virtual
drwxr-xr-x root root thermal
drwxr-xr-x root root thermal_zone0
-r--r--r-- root root temp
```

and even:

```
sudo strace -ff thinkfan -n 
[...]
openat(AT_FDCWD, "/sys/devices/virtual/thermal/thermal_zone0/temp", O_RDONLY) = 5
read(5, "53000\n", 128)                 = 6
write(2, "\n", 1)                       = 1
write(2, "/sys/devices/virtual/thermal/the"..., 75/sys/devices/virtual/thermal/thermal_zone0/temp: No such file or directory) = 75
```

So it opens the file, *reads* it, and then with an invented error?

**Comment by vmatare** [comment]
You're using the wrong keyword. `tp_thermal` is for the stuff in `/proc/acpi/ibm/thermal`, which has a completely different format. For temperature sources in sysfs you have to use the `hwmon` keyword.

**Comment by vmatare** [comment]
However the error message is indeed misleading, so that is a bug indeed.

**Comment by vmatare** [comment]
Huh. If I use the `tp_thermal` keyword with an hwmon sensor, I get:
```
ERROR: /sys/class/hwmon/hwmon0/temp1_input: Unknown file format.
```
Which is a (more) correct error message for this case.

**Comment by StyXman** [comment]
Hi @vmatare . That was a year ago. [According to Debian's archive](https://snapshot.debian.org/archive/debian/20190523T025328Z/pool/main/t/thinkfan/), it should have been 0.9.3 or so. I don't even have `thinkfan` installed anymore. If the current version shows a message like you shown, then you can consider this one closed.

**Comment by vmatare** [comment]
Great, thanks for the feedback!
