### ISSUE TITLE
Is it possible to also consider GPU temperature?

### ISSUE THREAD

**Issue by nightuser** [vmatare/thinkfan#73]
On some systems, you can also get information from the GPU sensor. Can we consider it too when choosing a fan speed level?

**Comment by vmatare** [comment]
Sure, you can add as many hwmon sensors as you like. Thinkfan doesn't care if it's your GPU or your pressure cooker.

**Comment by vmatare** [comment]
Btw, in case you're talking about a desktop computer and you want to control both the GPU, CPU, and possibly case fans as well, you'll need to try out the `multifan` branch.

**Comment by vmatare** [comment]
This is already documented sufficiently in the existing man page for the old config syntax. Man page for the YAML syntax is coming up.
