### ISSUE TITLE
invalid syntax error with whitespace between fan temperature and closing brace

### ISSUE THREAD

**Issue by rathann** [vmatare/thinkfan#76]
With thinkfan-1.0.2, this entry in `/etc/thinkfan.conf`
```
{ "64"
    (0 )
    (24)
}
```
causes:
```
ERROR: /etc/thinkfan.conf:6: Invalid syntax:
                                                          (0 )
                                                             ^
```
Removing the whitespace after `0` seems to resolve it. It took me a while to figure this out, especially since even the documentation `man thinkfan.conf` says this:
```man
   Complex Mode
       In  complex  mode,  both  the  lower-bound and upper-bound are lists of temperatures, the length of which must
       match the number of temperature readings thinkfan knows about.  Each bound must be enclosed  in  braces,  with
       individual values separated by commas or spaces, so the specific syntax of a complex mode fan level is:

              { fan-level
                  ( lower-1 [lower-2 ...] )
                  ( upper-1 [upper-2 ...] )
              }
```

**Comment by vmatare** [comment]
Thanks for the report. It should be fixed in `master` now. Note though that the old config syntax will soon be deprecated in favor of the new YAML syntax. The plan is to start warning about deprecation as soon as we have proper documentation for the YAML format.
