### ISSUE TITLE
Make install not working

### ISSUE THREAD

**Issue by BarbUk** [vmatare/thinkfan#88]
https://github.com/vmatare/thinkfan/commit/09260f4fa2813a7cf6c4215f06762a06ebe82746 is converting README to markdown, but [CMakeLists.txt:113](https://github.com/vmatare/thinkfan/blob/master/CMakeLists.txt#L113) try to install a README file.

**Comment by vmatare** [comment]
Right, thanks! I'll see about adding installation to the CI tests...

**Comment by vmatare** [comment]
Should be fixed now in `master`, `multifan` and `optional-sensors`

**Comment by BarbUk** [comment]
Installed the last master without issue, thanks.
