### ISSUE TITLE
ERROR: Module thinkpad_acpi doesn't seem to support fan_control

### ISSUE THREAD

**Issue by arm3nyn** [vmatare/thinkfan#94]
I got this error when I do : sudo thinkfan -q
ERROR: ~TpFanDriver: Resetting fan control in /proc/acpi/ibm/fan: Invalid argument
ERROR: Module thinkpad_acpi doesn't seem to support fan_control

that mesans not supported for thinkpad e470?

**Comment by vmatare** [comment]
Not necessarily, maybe you just haven't enabled the `fan_control` option on the `thinkpad_acpi` kernel module...

**Comment by vmatare** [comment]
https://www.kernel.org/doc/html/latest/admin-guide/laptops/thinkpad-acpi.html

**Comment by vmatare** [comment]
See also issue #45

**Comment by vmatare** [comment]
Closing for now, since I highly suspect it's the same issue as in #45

**Comment by arm3nyn** [comment]
Thank you

**Comment by mbernasocchi** [comment]
@vmatare I had enabled the `fan_control=1` and still had the error. adding èxperimental=1` removed the error and let thinkfan start. I put more details in #45
